version: '3'
services:
    node:
        image: node:12
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        volumes:
            - ./:/usr/src/app
        environment:
            - NODE_ENV
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run-script start-${NODE_ENV}"
        stop_signal: SIGINT

    mysql:
        image: mariadb:latest
        volumes:
            - .data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
